from sklearn.externals import joblib
from processLyrics import process

vectorizer = joblib.load('vectorizer.pk1')
classifier = joblib.load('classifier.pk1')

# input raw lyrics string
def predict(lyrics):
    processedLyrics = process([lyrics])
    vector = vectorizer.transform(processedLyrics).toarray()
    return classifier.predict(vector)

if __name__ == "__main__":
    hurt = "I hurt myself today To see if I still feel I focus on the pain The only thing that's real The needle tears a hole The old familiar sting Try to kill it all away But I remember everything What have I become My sweetest friend Everyone I know Goes away in the end And you could have it all My empire of dirt I will let you down I will make you hurt I wear this crown of shit Upon my liars chair Full of broken thoughts I cannot repair Beneath the stains of time The feelings disappear You are someone else I am still right here What have I become My sweetest friend Everyone I know Goes away in the end And you could have it all My empire of dirt I will let you down I will make you hurt If I could start again A million miles away I will keep myself I would find a way"
    happy = "It might seem crazy what I'm 'bout to say Sunshine she's here, you can take a break I'm a hot air balloon that could go to space With the air, like I don't care baby by the way Huh, because I'm happy Clap along if you feel like a room without a roof Because I'm happy Clap along if you feel like happiness is the truth Because I'm happy Clap along if you know what happiness is to you Because I'm happy Clap along if you feel like that's what you wanna do Here come bad news, talking this and that (Yeah) Well, give me all you got, and don't hold it back (Yeah) Well, I should probably warn you I'll be just fine (Yeah) No offense to you, don't waste your time Here's why Because I'm happy Clap along if you feel like a room without a roof Because I'm happy Clap along if you feel like happiness is the truth Because I'm happy Clap along if you know what happiness is to you Because I'm happy Clap along if you feel like that's what you wanna do Hey, come on, uh Bring me down, can't nuthin' (happy) Bring me down My level is too high to bring me down (happy) Can't nuthin', bring me down (happy) I said, let me tell you now, unh (happy) Bring me down, can't nuthin', bring me down (happy, happy, happy) My level is too high to bring me down (happy, happy, happy) Can't nuthin' bring me down (happy, happy, happy) I said Because I'm happy Clap along if you feel like a room without a roof Because I'm happy Clap along if you feel like happiness is the truth Because I'm happy Clap along if you know what happiness is to you Because I'm happy Clap along if you feel like that's what you wanna do Because I'm happy Clap along if you feel like a room without a roof Because I'm happy Clap along if you feel like happiness is the truth Because I'm happy Clap along if you know what happiness is to you Because I'm happy Clap along if you feel like that's what you wanna do Come on, unh bring me down can't nuthin' (happy, happy, happy) Bring me down my level is too high (happy, happy, happy) Bring me down can't nuthin' (happy, happy, happy) Bring me down, I said Because I'm happy Clap along if you feel like a room without a roof Because I'm happy Clap along if you feel like happiness is the truth Because I'm happy Clap along if you know what happiness is to you, eh eh eh Because I'm happy Clap along if you feel like that's what you wanna do Because I'm happy Clap along if you feel like a room without a roof Because I'm happy Clap along if you feel like happiness is the truth Because I'm happy Clap along if you know what happiness is to you, eh hey Because I'm happy Clap along if you feel like that's what you wanna do, heh come on"
    cstf = "Ah, yeah, ah, yeah I got this feelin' inside my bones It goes electric, wavy when I turn it on All through my city, all through my home We're flyin' up, no ceilin', when we in our zone I got that sunshine in my pocket Got that good soul in my feet I feel that hot blood in my body when it drops (ooh) I can't take my eyes up off it, movin' so phenomenally Room on lock, the way we rock it, so don't stop And under the lights when everything goes Nowhere to hide when I'm gettin' you close When we move, well, you already know So just imagine, just imagine, just imagine Nothin' I can see but you when you dance, dance, dance Feel a good, good creepin' up on you So just dance, dance, dance, come on All those things I shouldn't do But you dance, dance, dance And ain't nobody leavin' soon, so keep dancin' I can't stop the feelin' So just dance, dance, dance I can't stop the feelin' So just dance, dance, dance, come on Ooh, it's something magical It's in the air, it's in my blood, it's rushin' on (rushin' on) I don't need no reason, don't need control (need control) I fly so high, no ceiling, when I'm in my zone 'Cause I got that sunshine in my pocket Got that good soul in my feet I feel that hot blood in my body when it drops (ooh) I can't take my eyes up off it, moving so phenomenally Room on lock, the way we rock it, so don't stop (stop, stop, stop) Under the lights when everything goes Nowhere to hide when I'm gettin' you close When we move, well, you already know So just imagine, just imagine, just imagine Nothing I can see but you when you dance, dance, dance Feel a good, good, creepin' up on you So just dance, dance, dance, come on All those things I shouldn't do But you dance, dance, dance And ain't nobody leavin' soon, so keep dancin' I can't stop the feelin' So just dance, dance, dance I can't stop the feelin' So just dance, dance, dance I can't stop the feelin' So just dance, dance, dance I can't stop the feelin' (yeah) So keep dancin', come on Oh, yeah, yeah I can't stop the, I can't stop the I can't stop the, I can't stop the I can't stop the feelin' Nothin' I can see but you when you dance, dance, dance (I can't stop the feelin') Feel the good, good, creepin' up on you So just dance, dance, dance, come on (I can't stop the feelin') All those things I shouldn't do But you dance, dance, dance (dance, dance, dance) (I can't stop the feelin') And ain't nobody leavin' soon, so keep dancin' Everybody sing (I can't stop the feelin') Got this feeling in my body (I can't stop the feelin') Got this feeling in my body (I can't stop the feelin') Wanna see you move your body (I can't stop the feelin') Got this feelin' in my body Break it down Got this feelin' in my body (ah) Can't stop the feelin' Got this feelin' in my body, come on (ooh)"
    hello = "Hello, it's me I was wondering if after all these years you'd like to meet To go over everything They say that time's supposed to heal ya But I ain't done much healing Hello, can you hear me I'm in California dreaming about who we used to be When we were younger and free I've forgotten how it felt before the world fell at our feet There's such a difference between us And a million miles Hello from the other side I must have called a thousand times To tell you I'm sorry for everything that I've done But when I call you never seem to be home Hello from the outside At least I can say that I've tried To tell you I'm sorry for breaking your heart But it don't matter it clearly doesn't tear you apart anymore Hello, how are you? It's so typical of me to talk about myself I'm sorry I hope that you're well Did you ever make it out of that town where nothing ever happened It's no secret that the both of us Are running out of time So hello from the other side I must have called a thousand times To tell you I'm sorry for everything that I've done But when I call you never seem to be home Hello from the outside At least I can say that I've tried To tell you I'm sorry for breaking your heart But it don't matter it clearly doesn't tear you apart anymore Ooooohh, anymore Ooooohh, anymore Ooooohh, anymore Anymore Hello from the other side I must have called a thousand times To tell you I'm sorry for everything that I've done But when I call you never seem to be home Hello from the outside At least I can say that I've tried To tell you I'm sorry for breaking your heart But it don't matter it clearly doesn't tear you apart anymore"
    skinnylove = "Come on skinny love just last the year Pour a little salt we were never here My, my, my, my, my, my, my, my Staring at the sink of blood and crushed veneer I tell my love to wreck it all Cut out all the ropes and let me fall My, my, my, my, my, my, my, my Right in the moment this order's tall I told you to be patient I told you to be fine I told you to be balanced I told you to be kind In the morning I'll be with you But it will be a different kind I'll be holding all the tickets And you'll be owning all the fines Come on skinny love what happened here Suckle on the hope in lite brassiere My, my, my, my, my, my, my, my Sullen load is full; so slow on the split I told you to be patient I told you to be fine I told you to be balanced I told you to be kind Now all your love is wasted? Then who the hell was I? Now I'm breaking at the britches And at the end of all your lines Who will love you? Who will fight? Who will fall far behind? Come on skinny love My, my, my, my, my, my, my, my"
    thatbass = "Because you know I'm all about that bass, 'Bout that bass, no treble I'm all 'bout that bass, 'bout that bass, no treble I'm all 'bout that bass, 'bout that bass, no treble I'm all 'bout that bass, 'bout that bass Because you know I'm all about that bass, 'Bout that bass, no treble I'm all 'bout that bass, 'bout that bass, no treble I'm all 'bout that bass, 'bout that bass, no treble I'm all 'bout that bass (bass) I'm all about that, all about that bass I'm all about that, all about that bass I'm all about that bass, no treble We gon' take it to a whole another level We know that shit ain't real We know that shit ain't real We know that shit ain't real We know it's photoshoped We know that shit ain't real We know that shit ain't real We know that shit ain't real We know it's 'Cause you know I'm all about that bass, 'Bout that bass, no treble I'm all 'bout that bass, 'bout that bass, no treble I'm all 'bout that bass, 'bout that bass, no treble I'm all 'bout that bass, 'bout that bass Because you know I'm all about that bass, 'Bout that bass, no treble I'm all 'bout that bass, 'bout that bass, no treble I'm all 'bout that bass, 'bout that bass, no treble I'm all 'bout that bass"
    dancingqueen = "Ooh You can dance You can jive Having the time of your life Ooh, see that girl Watch that scene Dig in the dancing queen Friday night and the lights are low Looking out for a place to go Where they play the right music Getting in the swing You come to look for a king Anybody could be that guy Night is young and the music's high With a bit of rock music Everything is fine You're in the mood for a dance And when you get the chance You are the dancing queen Young and sweet Only seventeen Dancing queen Feel the beat from the tambourine, oh yeah You can dance You can jive Having the time of your life Ooh, see that girl Watch that scene Dig in the dancing queen You're a teaser, you turn 'em on Leave 'em burning and then you're gone Looking out for another Anyone will do You're in the mood for a dance And when you get the chance You are the dancing queen Young and sweet Only seventeen Dancing queen Feel the beat from the tambourine, oh yeah You can dance You can jive Having the time of your life Ooh, see that girl Watch that scene Dig in the dancing queen Dig in the dancing queen"
    eyeofthetiger = "Risin' up, back on the street Did my time, took my chances Went the distance, now I'm back on my feet Just a man and his will to survive So many times, it happens too fast You trade your passion for glory Don't lose your grip on the dreams of the past You must fight just to keep them alive It's the eye of the tiger, it's the thrill of the fight Risin' up to the challenge of our rival And the last known survivor stalks his prey in the night And he's watchin' us all with the eye of the tiger Face to face, out in the heat Hangin' tough, stayin' hungry They stack the odds 'till we take to the street For the kill with the skill to survive It's the eye of the tiger, it's the dream of the fight Risin' up to the challenge of our rival And the last known survivor stalks his prey in the night And he's watchin' us all with the eye of the tiger Risin' up, straight to the top Had the guts, got the glory Went the distance, now I'm not gonna stop Just a man and his will to survive It's the eye of the tiger, it's the dream of the fight Risin' up to the challenge of our rival And the last known survivor stalks his prey in the night And he's watchin' us all with the eye of the tiger The eye of the tiger The eye of the tiger The eye of the tiger The eye of the tiger"
    print(predict(hurt))
    print(predict(happy))
    print(predict(cstf))
    print(predict(hello))
    print(predict(skinnylove))
    print(predict(thatbass))
    print(predict(dancingqueen))
    print(predict(eyeofthetiger))
